spring:
  docker:
    compose:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/ajudante
    username: ajudante_user
    password: ThisIsMyStrongPassword
  jpa:
    hibernate:
      ddl-auto: validate
server:
  servlet:
    context-path: /cinzaerosa
